### ISSUE TITLE
minor cropping issues in pin photo

### ISSUE THREAD

**Issue by sergeyager** [sergeyager/sergeyager.github.io#8]
Girl hat photo:
 - the pin is mostly cropped out of the photo (photo needs to be adjusted slightly so the pin is in shot). photo looks good in the preview, it's the large version that's cropped awkwardly

![Untitled](https://user-images.githubusercontent.com/6903331/70385214-27d41300-1941-11ea-856d-e4915b3a8be4.png)

**Comment by Kimberleydillon** [comment]
@sergeyager Where are you viewing this? Cause on my laptop it looks okay. Is this the larger monitor? and if so what are the dimensions of your monitor so that I can add something for that size specifically. 
<img width="1358" alt="Screen Shot 2019-12-09 at 9 26 25 AM" src="https://user-images.githubusercontent.com/15920891/70458092-3b2cce80-1a66-11ea-8696-50b7bd5f2b2e.png">

**Comment by sergeyager** [comment]
It's on my main monitor, and it's reproducible on other wide screen monitors.

I'm not entirely sure what the measurements of my monitor are, but the problem seems to be on wider monitors, I can't quite give a specific ratio though :S

**Comment by sergeyager** [comment]
Here are some monitors that the cropping is happening on:

16:9 (1920x1080) and (2560x1440), also 16:10 (1920x1200)

**Comment by Kimberleydillon** [comment]
Fix my recropping the photo to make the pin more centered. Hopefully this works on all the monitors above. If further cropping is needed then we can re-open this ticket.
